export const INCOMING_CONNECTION = 'connection';
export const GET_QUEUES = 'GET_QUEUES';
export const SET_SELECTED_QUEUE_TYPE = 'SET_SELECTED_QUEUE_TYPE';
export const SET_SELECTED_QUEUE = 'SET_SELECTED_QUEUE';
